services:
  vault:
    container_name: vault
    hostname: $VAULT_NAME.$DOMAIN
    image: hashicorp/vault
    environment:
      VAULT_ADDR: http://$VAULT_NAME.$DOMAIN:8200
    restart: always
    volumes:
      - $VAULT_HOME/file:/vault/file
      - $VAULT_HOME/config:/vault/config
      - $VAULT_HOME/logs:/vault/logs
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault.json
    networks:
      - vault-network
  nginx:
    container_name: nginx
    hostname: $DOMAIN
    image: nginx
    restart: always
    volumes:
      - $NGINX_HOME/nginx.conf:/etc/nginx/nginx.conf
      - $CA_HOME/cert:/etc/nginx/conf.d/certs
    ports:
      - "80:80"
      - "443:443"
    networks:
      - vault-network

networks:
  vault-network:
    driver: bridge
    name: vault-network
