worker_processes 10;

events {
    worker_connections  4096;
}
http {
    proxy_send_timeout 120;
    proxy_read_timeout 300;
    proxy_buffering    off;
    proxy_request_buffering off;
    keepalive_timeout 30;
    client_body_buffer_size 1M;
    tcp_nodelay        on;
    proxy_ssl_session_reuse on;
    ssl_protocols TLSv1.2 TLSv1.3;
    server_names_hash_bucket_size 128;

    server {
        listen 80 default_server;
        server_name _;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name VAULT_NAME.DOMAIN;
        resolver 127.0.0.11 valid=30s;
        ssl_certificate     /etc/certs/chain-VAULT_NAME.pem;
        ssl_certificate_key /etc/certs/VAULT_NAME.key;

        location / {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto "https";
            set $upstream VAULT_NAME.DOMAIN;
            proxy_pass http://$upstream:8200;
        }
    }
}